package pl.softfly.integ.samples.invoice.jaxws.doc.transformation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.1
 */
@WebServiceClient(name = "DocumentTransformation", targetNamespace = "http://transformation.doc.jaxws.invoice.samples.integ.softfly.pl/", wsdlLocation = "http://localhost:8080/DocumentTransformation?wsdl")
public class DocumentTransformation
    extends Service {

  private final static URL DOCUMENTTRANSFORMATION_WSDL_LOCATION;
  private final static WebServiceException DOCUMENTTRANSFORMATION_EXCEPTION;
  private final static QName DOCUMENTTRANSFORMATION_QNAME = new QName(
      "http://transformation.doc.jaxws.invoice.samples.integ.softfly.pl/",
      "DocumentTransformation");

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL("http://localhost:8080/DocumentTransformation?wsdl");
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    DOCUMENTTRANSFORMATION_WSDL_LOCATION = url;
    DOCUMENTTRANSFORMATION_EXCEPTION = e;
  }

  public DocumentTransformation() {
    super(__getWsdlLocation(), DOCUMENTTRANSFORMATION_QNAME);
  }

  public DocumentTransformation(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  private static URL __getWsdlLocation() {
    if (DOCUMENTTRANSFORMATION_EXCEPTION != null) {
      throw DOCUMENTTRANSFORMATION_EXCEPTION;
    }
    return DOCUMENTTRANSFORMATION_WSDL_LOCATION;
  }

  /**
   * @return returns DocumentTransformationService
   */
  @WebEndpoint(name = "DocumentTransformationServicePort")
  public DocumentTransformationService getDocumentTransformationServicePort() {
    return super.getPort(
        new QName("http://transformation.doc.jaxws.invoice.samples.integ.softfly.pl/",
            "DocumentTransformationServicePort"), DocumentTransformationService.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *                 Supported features not in the <code>features</code> parameter will have their
   *                 default values.
   * @return returns DocumentTransformationService
   */
  @WebEndpoint(name = "DocumentTransformationServicePort")
  public DocumentTransformationService getDocumentTransformationServicePort(
      WebServiceFeature... features) {
    return super.getPort(
        new QName("http://transformation.doc.jaxws.invoice.samples.integ.softfly.pl/",
            "DocumentTransformationServicePort"), DocumentTransformationService.class, features);
  }

}
