package pl.softfly.integ.samples.invoice.jaxws.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import pl.softfly.integ.shipment.entity.ShipmentOutgoing;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.1
 */
@WebService(name = "SenderEndpointService", targetNamespace = "http://endpoint.jaxws.invoice.samples.integ.softfly.pl/")
@XmlSeeAlso({
    pl.softfly.integ.doc.entity.ObjectFactory.class,
    pl.softfly.integ.endpoint.entity.ObjectFactory.class,
    pl.softfly.integ.entity.ObjectFactory.class,
    pl.softfly.integ.samples.invoice.jaxws.endpoint.ObjectFactory.class,
    pl.softfly.integ.shipment.entity.ObjectFactory.class
})
public interface SenderEndpointService {


  /**
   * @param arg0
   * @return returns pl.softfly.integ.shipment.entity.ShipmentOutgoing
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "send", targetNamespace = "http://endpoint.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.endpoint.Send")
  @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://endpoint.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.endpoint.SendResponse")
  public ShipmentOutgoing send(
      @WebParam(name = "arg0", targetNamespace = "")
          ShipmentOutgoing arg0);

}
