package pl.softfly.integ.samples.invoice.jaxws.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.1
 */
@WebServiceClient(name = "SenderEndpoint", targetNamespace = "http://endpoint.jaxws.invoice.samples.integ.softfly.pl/", wsdlLocation = "http://localhost:8080/SenderEndpoint?wsdl")
public class SenderEndpoint
    extends Service {

  private final static URL SENDERENDPOINT_WSDL_LOCATION;
  private final static WebServiceException SENDERENDPOINT_EXCEPTION;
  private final static QName SENDERENDPOINT_QNAME = new QName(
      "http://endpoint.jaxws.invoice.samples.integ.softfly.pl/", "SenderEndpoint");

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL("http://localhost:8080/SenderEndpoint?wsdl");
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    SENDERENDPOINT_WSDL_LOCATION = url;
    SENDERENDPOINT_EXCEPTION = e;
  }

  public SenderEndpoint() {
    super(__getWsdlLocation(), SENDERENDPOINT_QNAME);
  }

  public SenderEndpoint(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  private static URL __getWsdlLocation() {
    if (SENDERENDPOINT_EXCEPTION != null) {
      throw SENDERENDPOINT_EXCEPTION;
    }
    return SENDERENDPOINT_WSDL_LOCATION;
  }

  /**
   * @return returns SenderEndpointService
   */
  @WebEndpoint(name = "SenderEndpointServicePort")
  public SenderEndpointService getSenderEndpointServicePort() {
    return super.getPort(new QName("http://endpoint.jaxws.invoice.samples.integ.softfly.pl/",
        "SenderEndpointServicePort"), SenderEndpointService.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *                 Supported features not in the <code>features</code> parameter will have their
   *                 default values.
   * @return returns SenderEndpointService
   */
  @WebEndpoint(name = "SenderEndpointServicePort")
  public SenderEndpointService getSenderEndpointServicePort(WebServiceFeature... features) {
    return super.getPort(new QName("http://endpoint.jaxws.invoice.samples.integ.softfly.pl/",
        "SenderEndpointServicePort"), SenderEndpointService.class, features);
  }

}
