package pl.softfly.integ.samples.invoice.jaxws.doc.validation.business;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import pl.softfly.integ.doc.entity.DocumentBusinessType;
import pl.softfly.integ.doc.entity.DocumentFormat;
import pl.softfly.integ.doc.entity.DocumentHeader;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.1
 */
@WebService(name = "DocumentValidationBusinessService", targetNamespace = "http://business.validation.doc.jaxws.invoice.samples.integ.softfly.pl/")
@XmlSeeAlso({
    pl.softfly.integ.doc.entity.ObjectFactory.class,
    pl.softfly.integ.endpoint.entity.ObjectFactory.class,
    pl.softfly.integ.entity.ObjectFactory.class,
    pl.softfly.integ.samples.invoice.jaxws.doc.validation.business.ObjectFactory.class,
    pl.softfly.integ.shipment.entity.ObjectFactory.class
})
public interface DocumentValidationBusinessService {


  /**
   * @param arg0
   * @return returns java.util.List<pl.softfly.integ.doc.entity.DocumentFormat>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getSupported", targetNamespace = "http://business.validation.doc.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.doc.validation.business.GetSupported")
  @ResponseWrapper(localName = "getSupportedResponse", targetNamespace = "http://business.validation.doc.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.doc.validation.business.GetSupportedResponse")
  public List<DocumentFormat> getSupported(
      @WebParam(name = "arg0", targetNamespace = "")
          List<DocumentBusinessType> arg0);

  /**
   * @param arg0
   * @return returns pl.softfly.integ.doc.entity.DocumentHeader
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "validate", targetNamespace = "http://business.validation.doc.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.doc.validation.business.Validate")
  @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://business.validation.doc.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.doc.validation.business.ValidateResponse")
  public DocumentHeader validate(
      @WebParam(name = "arg0", targetNamespace = "")
          DocumentHeader arg0);

}
