package pl.softfly.integ.samples.invoice.jaxws.doc.validation.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import pl.softfly.integ.doc.entity.DocumentHeader;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.1
 */
@WebService(name = "DocumentValidationSchemaService", targetNamespace = "http://schema.validation.doc.jaxws.invoice.samples.integ.softfly.pl/")
@XmlSeeAlso({
    pl.softfly.integ.doc.entity.ObjectFactory.class,
    pl.softfly.integ.endpoint.entity.ObjectFactory.class,
    pl.softfly.integ.entity.ObjectFactory.class,
    pl.softfly.integ.samples.invoice.jaxws.doc.validation.schema.ObjectFactory.class,
    pl.softfly.integ.shipment.entity.ObjectFactory.class
})
public interface DocumentValidationSchemaService {


  /**
   * @param arg0
   * @return returns pl.softfly.integ.doc.entity.DocumentHeader
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "validate", targetNamespace = "http://schema.validation.doc.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.doc.validation.schema.Validate")
  @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://schema.validation.doc.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.doc.validation.schema.ValidateResponse")
  public DocumentHeader validate(
      @WebParam(name = "arg0", targetNamespace = "")
          DocumentHeader arg0);

}
