package pl.softfly.integ.samples.invoice.jaxws.doc.validation.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.1
 */
@WebServiceClient(name = "DocumentValidationSchema", targetNamespace = "http://schema.validation.doc.jaxws.invoice.samples.integ.softfly.pl/", wsdlLocation = "http://localhost:8080/DocumentValidationSchema?wsdl")
public class DocumentValidationSchema
    extends Service {

  private final static URL DOCUMENTVALIDATIONSCHEMA_WSDL_LOCATION;
  private final static WebServiceException DOCUMENTVALIDATIONSCHEMA_EXCEPTION;
  private final static QName DOCUMENTVALIDATIONSCHEMA_QNAME = new QName(
      "http://schema.validation.doc.jaxws.invoice.samples.integ.softfly.pl/",
      "DocumentValidationSchema");

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL("http://localhost:8080/DocumentValidationSchema?wsdl");
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    DOCUMENTVALIDATIONSCHEMA_WSDL_LOCATION = url;
    DOCUMENTVALIDATIONSCHEMA_EXCEPTION = e;
  }

  public DocumentValidationSchema() {
    super(__getWsdlLocation(), DOCUMENTVALIDATIONSCHEMA_QNAME);
  }

  public DocumentValidationSchema(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  private static URL __getWsdlLocation() {
    if (DOCUMENTVALIDATIONSCHEMA_EXCEPTION != null) {
      throw DOCUMENTVALIDATIONSCHEMA_EXCEPTION;
    }
    return DOCUMENTVALIDATIONSCHEMA_WSDL_LOCATION;
  }

  /**
   * @return returns DocumentValidationSchemaService
   */
  @WebEndpoint(name = "DocumentValidationSchemaServicePort")
  public DocumentValidationSchemaService getDocumentValidationSchemaServicePort() {
    return super.getPort(
        new QName("http://schema.validation.doc.jaxws.invoice.samples.integ.softfly.pl/",
            "DocumentValidationSchemaServicePort"), DocumentValidationSchemaService.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *                 Supported features not in the <code>features</code> parameter will have their
   *                 default values.
   * @return returns DocumentValidationSchemaService
   */
  @WebEndpoint(name = "DocumentValidationSchemaServicePort")
  public DocumentValidationSchemaService getDocumentValidationSchemaServicePort(
      WebServiceFeature... features) {
    return super.getPort(
        new QName("http://schema.validation.doc.jaxws.invoice.samples.integ.softfly.pl/",
            "DocumentValidationSchemaServicePort"), DocumentValidationSchemaService.class,
        features);
  }

}
