package pl.softfly.integ.samples.invoice.jaxws.flows;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.1
 */
@WebServiceClient(name = "ForwardDocumentFlow", targetNamespace = "http://flows.jaxws.invoice.samples.integ.softfly.pl/", wsdlLocation = "http://localhost:8081/ForwardDocumentFlow?wsdl")
public class ForwardDocumentFlow
    extends Service {

  private final static URL FORWARDDOCUMENTFLOW_WSDL_LOCATION;
  private final static WebServiceException FORWARDDOCUMENTFLOW_EXCEPTION;
  private final static QName FORWARDDOCUMENTFLOW_QNAME = new QName(
      "http://flows.jaxws.invoice.samples.integ.softfly.pl/", "ForwardDocumentFlow");

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL("http://localhost:8081/ForwardDocumentFlow?wsdl");
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    FORWARDDOCUMENTFLOW_WSDL_LOCATION = url;
    FORWARDDOCUMENTFLOW_EXCEPTION = e;
  }

  public ForwardDocumentFlow() {
    super(__getWsdlLocation(), FORWARDDOCUMENTFLOW_QNAME);
  }

  public ForwardDocumentFlow(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  private static URL __getWsdlLocation() {
    if (FORWARDDOCUMENTFLOW_EXCEPTION != null) {
      throw FORWARDDOCUMENTFLOW_EXCEPTION;
    }
    return FORWARDDOCUMENTFLOW_WSDL_LOCATION;
  }

  /**
   * @return returns ForwardDocumentFlowService
   */
  @WebEndpoint(name = "ForwardDocumentFlowServicePort")
  public ForwardDocumentFlowService getForwardDocumentFlowServicePort() {
    return super.getPort(new QName("http://flows.jaxws.invoice.samples.integ.softfly.pl/",
        "ForwardDocumentFlowServicePort"), ForwardDocumentFlowService.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *                 Supported features not in the <code>features</code> parameter will have their
   *                 default values.
   * @return returns ForwardDocumentFlowService
   */
  @WebEndpoint(name = "ForwardDocumentFlowServicePort")
  public ForwardDocumentFlowService getForwardDocumentFlowServicePort(
      WebServiceFeature... features) {
    return super.getPort(new QName("http://flows.jaxws.invoice.samples.integ.softfly.pl/",
        "ForwardDocumentFlowServicePort"), ForwardDocumentFlowService.class, features);
  }

}
