package pl.softfly.integ.samples.invoice.jaxws.flows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.1
 */
@WebService(name = "ForwardDocumentFlowService", targetNamespace = "http://flows.jaxws.invoice.samples.integ.softfly.pl/")
@XmlSeeAlso({
    pl.softfly.integ.doc.entity.ObjectFactory.class,
    pl.softfly.integ.endpoint.entity.ObjectFactory.class,
    pl.softfly.integ.entity.ObjectFactory.class,
    pl.softfly.integ.samples.invoice.jaxws.flows.ObjectFactory.class,
    pl.softfly.integ.shipment.entity.ObjectFactory.class
})
public interface ForwardDocumentFlowService {


  /**
   * @param arg0
   * @return returns pl.softfly.integ.samples.invoice.jaxws.flows.ForwardDocumentFlowResponse
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "start", targetNamespace = "http://flows.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.flows.Start")
  @ResponseWrapper(localName = "startResponse", targetNamespace = "http://flows.jaxws.invoice.samples.integ.softfly.pl/", className = "pl.softfly.integ.samples.invoice.jaxws.flows.StartResponse")
  public ForwardDocumentFlowResponse start(
      @WebParam(name = "arg0", targetNamespace = "")
          String arg0);

}
